site_name: Ryan Seaman
nav:
  - Home: index.md
  - Publications: publications.md
theme:
  name: material
  features: 
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
      primary: green
      accent: deep orange
    - scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Switch to Light Mode
      primary: green
      accent: deep orange
repo_url: https://github.com/RPSeaman/RPSeaman.github.io
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
